# Generated by Django 5.0.2 on 2024-02-22 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus_manager', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
