# Generated by Django 5.0.2 on 2024-03-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus_manager', '0006_alter_paralleltext_verification1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paralleltext',
            old_name='source_text',
            new_name='english_text',
        ),
        migrations.RenameField(
            model_name='paralleltext',
            old_name='target_text',
            new_name='hindi_text',
        ),
        migrations.RenameField(
            model_name='paralleltext',
            old_name='verification1',
            new_name='verify_en_hi',
        ),
        migrations.RenameField(
            model_name='paralleltext',
            old_name='verification2',
            new_name='verify_en_mn',
        ),
        migrations.RenameField(
            model_name='paralleltext',
            old_name='verification3',
            new_name='verify_hi_mn',
        ),
        migrations.RemoveField(
            model_name='paralleltext',
            name='verification4',
        ),
        migrations.RemoveField(
            model_name='paralleltext',
            name='verification5',
        ),
        migrations.AddField(
            model_name='paralleltext',
            name='manipuri_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
