# Generated by Django 5.0.2 on 2024-03-07 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus_manager', '0007_rename_source_text_paralleltext_english_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paralleltext',
            old_name='english_text',
            new_name='en_text',
        ),
        migrations.RenameField(
            model_name='paralleltext',
            old_name='hindi_text',
            new_name='hi_text',
        ),
        migrations.RenameField(
            model_name='paralleltext',
            old_name='manipuri_text',
            new_name='mn_text',
        ),
    ]
