# Generated by Django 5.0.2 on 2024-03-14 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus_manager', '0008_rename_english_text_paralleltext_en_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paralleltext',
            name='verify_en_hi',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='paralleltext',
            name='verify_en_mn',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='paralleltext',
            name='verify_hi_mn',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.CreateModel(
            name='DeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('parallel_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus_manager.paralleltext')),
            ],
        ),
    ]
