# Generated by Django 5.0.2 on 2024-03-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus_manager', '0009_alter_paralleltext_verify_en_hi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paralleltext',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
